---
- name: update API package manager repositories cache
  apt:
    update_cache: yes

- name: Install unzip package
  apt: name=unzip state=present

- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest

- name: Ensure Java is installed.
  apt:
    name: "{{ java_packages }}"
    state: present
