---

- name: Remove old tomcat
  file:
    path: "{{ tomcat_home }}"
    state: absent
  ignore_errors :  true

- name: Download Tomcat
  get_url:
    url: "{{ tomcat_download_url }}" 
    dest: "{{ tomcat_download_dir }}"

- name: Extract archive
  unarchive:
    src: "{{ tomcat_download_dir }}"
    dest: "{{ tomcat_extracr_dir }}"
    remote_src: true
    owner: root
    group: root

- name: Remove downloaded tar file
  file:
    path: "{{ tomcat_download_dir }}"
    state: absent  
  
- name: start tomcat
  shell: sh /opt/apache-tomcat-9.0.36/bin/startup.sh
